repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
        types: [python]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        language_version: python3
        types: [python]
        args:
          - --remove-all-unused-imports
          - --recursive
          - --in-place